name: New Script Request
description: Request that a new script be produced to solve a problem or streamline a workflow.
title: "[Script Request]: "
labels: ["request", "triage"]
assignees:
  - fresher-unnamed-0b
body:
  - type: markdown
    attributes:
      value: |
        # New Script Request  
        Request that a new script be produced to solve a problem or streamline a workflow.
  - type: input
    id: service_area
    attributes:
      label: Service or Area
      description: What service should this script work with?
      placeholder: e.g. Intune, Exchange, Entra ID
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary of Request
      description: What would you like this script to do?
      placeholder: e.g. "Output a CSV of all devices enrolled into Intune."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details or Specific Requirements
      description: Is there any extra information that would be useful?
      placeholder: e.g. "Can the CSV file include the serial numbers of the machines?"
    validations:
      required: false
